services:
  chameleon:
    build: .
    environment:
      CHAMELEON_POSTGRES_URL: postgres://postgres:password@postgres:5432/chameleon
    ports:
      - 3000:3000
    restart: unless-stopped
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: chameleon
      POSTGRES_PASSWORD: password

