[build]
dist = "dist"
target = "./crates/chameleon-frontend/index.html"

[clean]
dist = "dist"

[[proxy]]
backend = "ws://localhost:3000/ws/v1"
ws = true

[[proxy]]
backend = "http://localhost:3000/api/v1/"
